#spring:
#  datasource:
#    url: jdbc:h2:./devdb #persistance db config
#    username:  test
#  jpa:
#    hibernate:
#      ddl-auto: update   #update db config


spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none